version: '3'

services:
  prize-service:
    build:
      context: ./../prize-service
      dockerfile: ./../prize-service/prize-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/var/lib/redis/data/
  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: restaurants
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db 