version: '3'

services:
  prize-service:
    build:
      context: ./../prize-service
      dockerfile: ./../prize-service/prize-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/var/lib/redis/data/